name: gameoflife project build
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the git
        uses: actions/checkout@v4
      - name: use java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: create package using mvn package
        run: mvn package
      - name: create directory for upload artifacts
        run: mkdir dev && cp gameoflife-web/target/gameoflife.war dev
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: dev
      
